name: portfolio_flutter
description: This is my portfolio website on flutter.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.8.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - images/background/
    - images/logo/
    - images/
